#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import argparse
import sys
from time import sleep
from datetime import datetime

try:
    from urllib.request import urlopen
except ImportError:
    from urllib import urlopen


parser = argparse.ArgumentParser(description='Monitora links')
parser.add_argument('urls', metavar='URL', nargs='+',
                    help='URL para monitorar')
parser.add_argument('-n', dest='monit', action='store_false', default=True,
                    help='Não fica monitorando, verifica apenas uma vez')


def main():
    args = parser.parse_args()

    args.urls = list(add_prefix(args.urls))

    try:
        while True:
            for url in args.urls:
                verify_url(url)
            if not args.monit:
                sys.exit()
            sleep(10)
    except KeyboardInterrupt:
        print('Saindo :)')
        sys.exit(0)


def add_prefix(urls, output=sys.stderr):
    for url in urls:
        if not url.startswith('http'):
            url = 'http://' + url
            if output:
                print('A url não inicia com http:// ou https://', file=output)
                print('Adicionando, a url monitorada será:', url, file=output)
        yield url


def verify_url(url, output=sys.stdout):
    date = datetime.today()
    try:
        code = urlopen(url).getcode()
        if code == 200:
            print('%s - Sucesso na conexão com o domínio' % date, url, file=output)
            return True
    except:
        pass
    print('%s - Falha na conexão com o domínio' % date, url, file=output)
    return False

if __name__ == '__main__':
    main()
