#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import sys
from time import sleep
from datetime import datetime
from urllib import urlopen


parser = argparse.ArgumentParser(description='Monitora links')
parser.add_argument('url', metavar='URL',
                    help='URL para monitorar')
parser.add_argument('-n', dest='monit', action='store_false', default=True,
                    help='Não fica monitorando, verifica apenas uma vez')


def main():
    args = parser.parse_args()

    while True:
        if not args.url.startswith('http'):
            print 'A url não inicia com http:// ou https://'
            print 'Adicionando, a url monitorada será:'
            args.url = 'http://' + args.url
            print args.url
        verify_url(args.url)
        if args.monit:
            try:
                sleep(10)
            except KeyboardInterrupt:
                print 'Saindo :)'
                sys.exit(0)
        else:
            sys.exit()


def verify_url(url):
    date = datetime.today()
    try:
        code = urlopen(url).getcode()
        if code == 200:
            print '%s - Sucesso na conexão com o domínio' % date
        else:
            print '%s - Falha na conexão com o domínio' % date
    except:
        print '%s - Falha na conexão com o domínio' % date

if __name__ == '__main__':
    main()
